/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectop2_germanfigueroa;

import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import javax.swing.JButton;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;

/**
 *
 * @author gafm2
 */
public class Principal extends javax.swing.JFrame {
    private JPanel paletaPanel;
    private LienzoDiagrama lienzoPanel;
    private JTextArea codigoGeneradoArea;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        lienzoPanel = new LienzoDiagrama();
        codigoGeneradoArea = new JTextArea();
        
        codigoGeneradoArea.setBackground(new Color(30, 30, 30));
        codigoGeneradoArea.setForeground(Color.CYAN);
        codigoGeneradoArea.setFont(new Font("Consolas", Font.PLAIN, 14));
        
        Component scrollLienzo = new JScrollPane(lienzoPanel);
        this.add(scrollLienzo, BorderLayout.CENTER);
        
        Component scrollCodigo = new JScrollPane(codigoGeneradoArea);
        this.add(scrollCodigo, BorderLayout.EAST);
        
        this.revalidate();
        
        pnl_paleta.setLayout(new java.awt.GridLayout(8, 1, 0, 5));
        pnl_paleta.setBackground(new Color(50, 50, 50));
        pnl_paleta.setPreferredSize(new java.awt.Dimension(180,0));
        
        BotonFormaUML btnInicio = new BotonFormaUML("Inicio", "inicio");
        BotonFormaUML btnIf = new BotonFormaUML("Si/No (If)", "if");
        BotonFormaUML btnSout = new BotonFormaUML("Imprimir", "sout");
        BotonFormaUML btnOperacion = new BotonFormaUML("Operacion", "operacion");
        BotonFormaUML btnFor = new BotonFormaUML("Bucle (For)", "for");
        BotonFormaUML btnWhile = new BotonFormaUML("Bucle (While)", "while");
        BotonFormaUML btnFin = new BotonFormaUML("Fin", "fin");
        
        pnl_paleta.add(btnInicio);
        pnl_paleta.add(btnOperacion);
        pnl_paleta.add(btnIf);
        pnl_paleta.add(btnFor);
        pnl_paleta.add(btnWhile);
        pnl_paleta.add(btnSout);
        pnl_paleta.add(btnFin);
        
        this.add(pnl_paleta, BorderLayout.WEST);
        
        btnInicio.addActionListener(e -> {
            FiguraUML f = new FiguraUML("Inicio", 50, 50);
            lienzoPanel.add(f);
            lienzoPanel.repaint();
        });
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_paleta = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_paleta.setMinimumSize(new java.awt.Dimension(180, 500));
        pnl_paleta.setPreferredSize(new java.awt.Dimension(180, 500));
        pnl_paleta.setLayout(new java.awt.GridLayout(8, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnl_paleta, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 418, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(pnl_paleta, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnl_paleta;
    // End of variables declaration//GEN-END:variables
}
